#!/bin/sh /etc/rc.common

START=99
STOP=15

USE_PROCD=1

WATCHDOG=/usr/sbin/ybwatchdog.sh
CLIENT=/usr/sbin/ybclient.lua

start_service() {
	if [ $(uci get ybclient.client.enable 2>/dev/null) -eq 0 ]; then 
		exit
	fi
	
	$CLIENT $(uci get ybclient.client.username) $(uci get ybclient.client.password) $(uci get ybclient.client.type) login

	if [ $(uci get ybclient.client.watchdog 2>/dev/null) -eq 1 ]; then 
		procd_open_instance "ybclient-watchdog"
		procd_set_param command 
		procd_set_param stdout 1
		procd_set_param stderr 1
		procd_set_param respawn ${respawn_threshold:-36000} ${respawn_timeout:-1} ${respawn_retry:-10000}
		procd_set_param pidfile /var/run/ybclient-watchdog.pid
		procd_close_instance
	fi
}

service_triggers() {
        procd_add_reload_trigger "ybclient"
}
